<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNet.Mvc.zh-Hans" Version="5.2.6" />
    <PackageVersion Include="Microsoft.AspNet.Razor.zh-Hans" Version="3.2.6" />
    <PackageVersion Include="Microsoft.AspNet.WebPages.zh-Hans" Version="3.2.6" />
    <PackageVersion Include="NewLife.Agent" Version="10.13.2025.604" />
    <PackageVersion Include="NewLife.Core" Version="11.5.2025.701" />
    <PackageVersion Include="NewLife.Cube" Version="6.5.2025.701" />
    <PackageVersion Include="NewLife.Cube.Core" Version="6.5.2025.701" />
    <PackageVersion Include="NewLife.Net" Version="4.4.2025.705" />
    <PackageVersion Include="NewLife.Stardust" Version="3.4.2025.701" />
    <PackageVersion Include="NewLife.Stardust.Extensions" Version="3.4.2025.701" />
    <PackageVersion Include="NewLife.XCode" Version="11.19.2025.701" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>