<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net45;net8.0</TargetFrameworks>
    <AssemblyName>NewLife.DNSServer</AssemblyName>
    <AssemblyTitle>新生命DNS代理服务器</AssemblyTitle>
    <Description>某个域名解析到哪个IP上，你说了算，如果你不指定，就由上级DNS服务器说了算</Description>
    <Company>新生命开发团队</Company>
    <Copyright>©2002-2026 NewLife</Copyright>
    <VersionPrefix>4.0</VersionPrefix>
    <VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
    <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(VersionPrefix).*</AssemblyVersion>
    <Deterministic>false</Deterministic>
    <OutputPath>..\Bin\Server</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Doc\newlife.snk</AssemblyOriginatorKeyFile>
    <NoWarn>1701;1702;NU5104;NETSDK1138;CS7035</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NewLife.Agent" />
    <PackageReference Include="NewLife.Net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewLife.DNS\NewLife.DNS.csproj" />
  </ItemGroup>
</Project>