<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45;netstandard2.0</TargetFrameworks>
    <AssemblyName>NewLife.DNS</AssemblyName>
    <AssemblyTitle>新生命DNS代理服务器</AssemblyTitle>
    <Description>新生命DNS代理服务器</Description>
    <Company>新生命开发团队</Company>
    <Copyright>©2002-2026 NewLife</Copyright>
    <VersionPrefix>4.0</VersionPrefix>
    <VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
    <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(VersionPrefix).*</AssemblyVersion>
    <Deterministic>false</Deterministic>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>$(AssemblyName)</PackageId>
    <Authors>$(Company)</Authors>
    <ProjectUrl>https://github.com/NewLifeX</ProjectUrl>
    <PackageIconUrl>http://www.NewLifeX.com/favicon.ico</PackageIconUrl>
    <RepositoryUrl>https://github.com/NewLifeX/NewLife.DNS</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>新生命团队;X组件;NewLife;$(AssemblyName)</PackageTags>
    <PackageReleaseNotes>新生命DNS代理服务器</PackageReleaseNotes>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NewLife.XCode" />
  </ItemGroup>
</Project>